name: Continous Delivery
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [security-audit, static-analysis]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build

  # lint:
  #   runs-on: ubuntu-latest
  #   needs: [security-audit, static-analysis]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Install Dependecies
  #       run: npm i
  #     - name: Lint the code
  #       run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [security-audit, static-analysis]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Run Unit Tests
        run: npm t

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check for security issue
        run: npm audit --audit-level=critical

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with: 
          languages: javascript
      - name: Perform Analysis
        uses: github/codeql-action/analyze@v1
